### ISSUE TITLE
Ability to add custom and additional details to JWT token

### ISSUE THREAD

**Issue by subhendukundu** [authc1/authc1#3]
Custom claims are missing to add extra details to our jwt token.
In addition this we might need to provide additional tokens which can be used in machines/servers to write/update user details in AuthC1

**Comment by notpritam** [comment]
I would love to contribute to this, but i might need a little guidance...

**Comment by subhendukundu** [comment]
Hey @notpritam We had just closed this with commit [e7e2ba2](https://github.com/authc1/authc1/commit/e7e2ba248633d49ab58e325ee2e1ae4e9ba60a1c)
But I would love your contribution on few other things. Such as, recreating our homepage. If you look at https://authc1.com right now very basic to almost nothing. Do you think you can help there?

**Comment by notpritam** [comment]
Yes , i would love to contribute there also, let me know what help you wanted, i am both designer and developer also, so i would be great fit for redesigning the landing page.

**Comment by subhendukundu** [comment]
Yes, I saw your profile. Really good. I think let’s brainstorm on a concept, how our landing page should look like, what kind of data we want to showcase. What will come to your mind when they see our website etc.
Maybe we can showcase benchmarks, performance, how to can scale to millions without an issue. Also let’s create an issue on this then assign it to yourself?

**Comment by notpritam** [comment]
okay great..
where should we discuss about this ?
like do you have any social platform in mind or should we do this in that issue comment section
